### ISSUE TITLE
List all repositories that are open source

### ISSUE THREAD

**Issue by JoshSmith** [presidential-innovation-fellows/code-gov-web#125]
I am assuming that the intention is to list every open source repository created by Federal agencies on this website.

If not, I would really like to see a list of all of them and prefer that you feature ones that you think deserve special recognition.

Right now, seeing all the repos for any given agency is a 4-5 step process otherwise: click on the agency, click on the project, click on the link to the repo, click on the acknowledgement that I clicked a link, click on the organization name on GitHub.

I know this was just recently launched (🎉 !), so please take my feedback as someone coming in completely cold to the project.

**Comment by lukad03** [comment]
@JoshSmith We plan on adding more and more repos as Agencies make us aware of their open source repos.

On the UX side – as we get more repos, we plan on enabling other methods to explore them. We're hoping to expand the data we're capturing about repos to make it easier for developers to find repos that match their interests - i.e. language, framework, etc. Any suggestions you have are welcome!

**Comment by JoshSmith** [comment]
@lukad03 I'm fairly certain CFPB has more repos than displayed here.

I'd be happy to provide more suggestions here. Also have a massive ~4,000 entry long list of languages, frameworks, etc. that we use in @code-corps to provide some matching utility.

**Comment by IanLee1521** [comment]
Hi @lukad03 - how are you going to want those projects / repos provided? Pull request to the repos.json file? Would it make sense to have some method to build that file from a collections of repo lists?

**Comment by mattbailey0** [comment]
Hi @JoshSmith - the basic plan at launch was to highlight a number of projects that agencies volunteered for inclusion.  That is dramatically different from the approach starting 120 days after the issuance of the policy (today marks 90 days). At 120 days, every* agency is required to publicly post an "enterprise code inventory" which catalogs their custom code, including open source projects and projects that are not open source, in the form of a .json file on their agency website.  Code.gov will harvest those to create a comprehensive listing.

The sky's the limit in terms of what else we do with the platform in terms of how we present and highlight open source repositories.  Generally, we've been thinking in terms of two use cases:
1) helping agencies find code that already exists and which meets their needs, rather than building from scratch or paying for it unnecesarily
2) helping the open source community discover and contribute to government open source projects - and conversely, helping agencies learn how to contribute back to the community

* not all "agencies" are subject to the Federal Source Code policy. For example, while CFPB is represented on the site, it is an independent agency and doesn't have to participate.

**Comment by JoshSmith** [comment]
Can you share some insight into why this has been closed?
