### ISSUE TITLE
Fix Modal Width

### ISSUE THREAD

**Issue by lukad03** [presidential-innovation-fellows/code-gov-web#133]
![620e1986-a26a-11e6-97f8-b7f8ee34f481](https://cloud.githubusercontent.com/assets/2506817/20012160/7df97b9e-a284-11e6-9cf1-aed0c9c86390.png)

Links exceed modal width

via @hamitron

**Comment by bodnarbm** [comment]
I did some testing and it seems like this can be fixed by setting `overflow-wrap` (for modern browsers) and `word-wrap` (for older browsers) to `break-word`. That will ensure that the URL breaks with the modal. Making that change makes that modal look like this.

<img width="615" alt="screen shot 2016-11-04 at 8 21 31 pm" src="https://cloud.githubusercontent.com/assets/121035/20026199/c139de50-a2cd-11e6-8517-abc67e135ceb.png">

I committed the css change to my fork and can make a PR if you want.

However, I think the modal size does not work well on mobile screens. In fact, it seems like overall the repo pages need work for mobile sizes. Maybe a new issue?

**Comment by lukad03** [comment]
@bodnarbm A PR to start on fixing the link breaks would be great. I can work on mobile-friendly modals early next week.

**Comment by bodnarbm** [comment]
Thanks @lukad03. PR Submitted.

**Comment by lukad03** [comment]
Fixed by https://github.com/presidential-innovation-fellows/code-gov-web/issues/159.
