### ISSUE TITLE
Does the dist directory contain the source files?

### ISSUE THREAD

**Issue by ascott1** [presidential-innovation-fellows/code-gov-web#18]
I noticed a `src` directory that contains only images, which raised this question. If I am a contributor, should I edit the HTML and CSS files in `dist` in my pull request? If so, it may be worth noting this in the README as `dist` typically represents the outputted code rather than the source files.

Thanks! I'm excited to see this site take shape!

**Comment by rossdakin** [comment]
Hi @ascott1!

Great observation. The only real "source" file in this repo is that image (a high-Res version of the more compressed copy found in dist).

Because it's such a simple site for now, WYSIWYG in the dist folder -- it's not derivative of any additional source. Feel free to open PRs against it directly. 

Thanks for your interest!

💪🖥🇺🇸
