### ISSUE TITLE
Add the NSA Repositories

### ISSUE THREAD

**Issue by trevor-vaughan** [presidential-innovation-fellows/code-gov-web#183]
I would like to vote to have the NSA repos added to the list.

Main Page: https://github.com/nationalsecurityagency
IAD: https://github.com/iadgov

**Comment by okamanda** [comment]
Thanks for sending this along @trevor-vaughan. We'll take a look and update the code inventories.

**Comment by jbjonesjr** [comment]
Intelligence community fight!!

![](https://67.media.tumblr.com/705ad3ac6c81f4a3b64a02c7696b81c6/tumblr_nxp7kqiVg01tp80nvo1_500.gif)

Probably worth adding NGA as well: https://github.com/ngageoint

cc/ @ckras34

**Comment by trevor-vaughan** [comment]
@okamanda I'm not quite sure how you want to handle this type of situation, but the NSA [SIMP](https://github.com/nationalsecurityagency/simp) project got too big to be fully housed over there and moved to [its own space](https://github.com/simp).

Everything in that space is under the SIMP project and part of the stack and almost all of it can be used in a standalone manner.

I guess I'll just leave this info here and see how you run with it (or not) as a reference for future projects.

**Comment by trevor-vaughan** [comment]
@jbjonesjr Oh come now, it's just a bit of previously unheard of public collaboration at scale!

**Comment by ctubbsii** [comment]
@trevor-vaughan NSA has a GitHub pages site at https://nationalsecurityagency.github.io/ with some information about open source software releases, in a human-readable form, and it includes SIMP. A code.json file there would be better. It doesn't look like there exists one at https://www.nsa.gov/code.json but I think it makes more sense at the github.io pages site, with (much of) the actual code.

I wonder... Would code.gov pull a code.json file from a github.io site instead of an agency's .gov site? How can code.gov verify that a particular GitHub repo is controlled by a particular Government Agency? Would it pull it over HTTP instead of HTTPS? Trusting a secure (HTTPS) .gov seems like it would be more reliable if code.gov wanted to make sure they only inventoried legit sources.

I suppose Agencies could publish a code.json on a github.io pages site with a custom domain (CNAME). For example, code.nsa.gov. However, GitHub still doesn't support HTTPS for custom domains (in spite of the lively discussion at places such as isaacs/github#156), so it couldn't be grabbed from a trusted HTTPS location.

Another question, given the items listed at NSA's Github.io page, is: who is responsible for inventorying software produced by an agency and forked by another? or software which, by means of having a suitable license grant, is now maintained by another entity (like Apache, others)?

I wonder also if it would have been better to inventory "releases" rather than development repositories. The Apache Software Foundation has a concept of a "[release][1]", which is a distinct snapshot artifact of a repository, with certain legal declarations which distinguish it from publicly available interim states which might exist in development repositories. With SIMP, and other projects being maintained in various states in various forks and repositories, having a concept of a "release" to inventory would be a lot easier. Having a central repository of "released" government software artifacts, like [Maven Central][2], instead of just an inventory, would be even better. However, that only works if there's a "released" concept separate from "publicly accessible" or "open source". A central repository would also dramatically simplify things for developers... and a repository could have rules which reject malformed artifacts (those with insufficient metadata).

[1]: https://www.apache.org/dev/release-publishing.html
[2]: https://search.maven.org/

**Comment by trevor-vaughan** [comment]
@ctubbsii Well, I'm fine with tracking releases https://github.com/NationalSecurityAgency/SIMP/releases but it's extra work on most projects.

In terms of publishing to a formal `.gov` site, it's a good idea but getting something out there is WAY more difficult than pushing something to a repo that the dev team controls. The same is true of pushing something to the root level of the NSA GitHub page for instance.

For a central repository, that was sort of the question that I had regarding a PR vs just telling someone where the software is. In theory, what is being built here *is* a central repository. But, yes, it would be nice if an Agency would step up and curate this officially as a project with oversight, a mission statement, and longevity. We keep having these things pop up randomly and we have no idea when or where they will appear because it's a lot of small, well meaning, groups instead of a formal assignment ( I think ).

In theory, either the Executive branch or GAO would be logical groups to own this since one is telling us to do things and the other is making sure we aren't horrible at doing them.

**Comment by ckaran** [comment]
@trevor-vaughan what about the National Archives?  They're good at longevity.

**Comment by trevor-vaughan** [comment]
@ckaran Honestly, any org that feels the calling to keep things running would be good. I was just throwing things out as possibilities, I don't actually have any ability to influence anything at all but, if you make enough noise on the Internet, someone might listen :smile:

**Comment by trevor-vaughan** [comment]
Just checking to see if there was any movement here. A lot of people are starting to talk about code.gov and it would be *great* to be able to start rolling the projects in.

**Comment by okamanda** [comment]
@AlvandSalehi @mattbailey0, can we connect @trevor-vaughan with DOD agency contact for code.gov?

**Comment by ckras34** [comment]
Who is DoD's POC? I'm happy to discuss moving some high-traffic NGA repos over the DoD bucket on code.gov if it will improve long-term health.

**Comment by ckaran** [comment]
@ckras34 try talking with @shawoods; she is leading the [code.mil](http://code.mil) effort.  If you have trouble getting in contact with her, message me directly via email and I'll try to help out.

**Comment by okamanda** [comment]
NSA [repos have now been added to code.gov](https://code.gov/#/explore-code/agencies/NSA) thanks @trevor-vaughan!

https://code.gov/#/explore-code/agencies/NSA
