### ISSUE TITLE
Concern over hosting all projects on github

### ISSUE THREAD

**Issue by mikeBeviBevi** [presidential-innovation-fellows/code-gov-web#228]
I'm not sure if this already went out for a bid, but I think hosting all of the federal governments code on github is showing a favoritism toward github's service that is offered by many other companies.  I assume that having the distinction of being the federal governments choice for open source code hosting would give a company a real investment advantage.  I'm hoping to raise this concern now to avoid any law suits in the future.  Sorry if this isn't the appropriate repo to raise this issue.

**Comment by 4T0M1Cdevsec** [comment]
Did we forget that we can host our own platforms, even if it is powered by GitHub. Do you think web server software went out for bid or did agencies just start using coldfusion/PHP/[insert language of choice].  Also, how does it work for bidding on a free platform?

**Comment by mikeBeviBevi** [comment]
@jbjonesjr Thanks, that clears up my question.  @4tom1Cdevsec you are correct, fed gov does host its own public facing web servers.  My concern is that even if it is a free service, the federal government cannot really endorse that product over another and so far all code that Ive seen related to this initiative has been on github. Also, nothing is ever "free".  All that being said,  I think this issue can be considered resolved "WAD"  as far as I'm concerned.

**Comment by cmurphyUSAID** [comment]
Just some clarification of procurement...

@4T0M1Cdevsec  Procuring does not always require a bidding process.  It should always involve analysis of alternatives, though.  Just because something is free does not mean the licensing is in order or all the features are a good fit.  

Public-facing code hosting is pretty low cost and relatively easy to move around, so the analysis does not need to be a long drawn out process, but some assumptions to keep in mind for the analysis should probably be 

- how easy is it to move when we have 100, 1,000 projects
- how much of a pain would it be if the existing site suddenly became unsable

**Comment by jbjonesjr** [comment]
Just for future reference to anyone finding this thread in the future:

> does not mean the licensing is in order or all the features are a good fit.

**GSA** & **GitHub** negotiated customer terms of service to better meet the needs of the Government customer. You can find those [here](https://help.github.com/articles/amendment-to-github-terms-of-service-applicable-to-u-s-federal-government-users/)

**Comment by okamanda** [comment]
Thanks @mikeBeviBevi
