### ISSUE TITLE
Include a button/link to Github Issues to encourage Public Participation/Feedback

### ISSUE THREAD

**Issue by JJediny** [presidential-innovation-fellows/code-gov-web#77]
A button should be added under `Read the Policy` for `Join the Discussion` or akin

**Comment by IanLee1521** [comment]
There are a couple of pull requests pending for adding this. #9 was one that didn't get merged, and so I recreated it in #42 

Apparently now *that* pull request is out of date because that file was removed in the latest master... Might need to just wait until the upcoming launch, though @mattbailey0  or @lukad03 might be able to shed some more light.

**Comment by mattbailey0** [comment]
Hi both - you're spot on. We have held off on any but very minimal changes to the current site pending launch.
